### ISSUE TITLE
CWM Crashing PebbleHost Server on Startup (1.18.1)

### ISSUE THREAD

**Issue by AshrielV** [ZuzAser80/CWM#1]
Below see the error log as it begins to fail. If you would like the entire log I can provide one. I was using ColdWeaponsMod-1.0.1.jar.

07.02 14:18:02 [Server] main/FATAL Failed to start the minecraft server
07.02 14:18:02 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cwm'!
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
07.02 14:18:02 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
07.02 14:18:02 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
07.02 14:18:02 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
07.02 14:18:02 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
07.02 14:18:02 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
07.02 14:18:02 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
07.02 14:18:02 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_897
07.02 14:18:02 [Server] INFO at net.zuz.cwm.CWMMain.onInitialize(CWMMain.java:37) ~[ColdWeaponsMod-1.0.1.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO ... 15 more
07.02 14:18:02 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.class_897
07.02 14:18:02 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
07.02 14:18:02 [Server] INFO at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
07.02 14:18:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
07.02 14:18:02 [Server] INFO at net.zuz.cwm.CWMMain.onInitialize(CWMMain.java:37) ~[ColdWeaponsMod-1.0.1.jar:?]
07.02 14:18:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
07.02 14:18:02 [Server] INFO ... 15 more
07.02 14:18:02 [PebbleHost Loader] Server Stopped
07.02 14:18:02 [PebbleHost Loader] PebbleHost Server Loader Stopping...
07.02 14:18:02 [PebbleHost Loader] Server loader version: v3.0.4 (using configuration version v1.3.6)
07.02 14:18:02 [PebbleHost Loader] PebbleHost Server Loader Stopped.
07.02 14:18:02 [PebbleHost] Server stopped

**Comment by ZuzAser80** [comment]
Hi, sorry i couldn't respond earlier, but it first of all: are you playing with CWM only or some other mods? Second: please, provide me a full log, but ill fix what i saw here, give me little bit of time.

**Comment by ZuzAser80** [comment]
And yes it may be problem on the PebbleHost's side, but ill try to hotfix the mod asap

**Comment by ZuzAser80** [comment]
Try setting up the server using different host if possible, that's my best advise for now lmfao

**Comment by ZuzAser80** [comment]
Hmu if you will find more bugs
